# Preprocessing data

In [19]:
import os
import pandas as pd

## Preprocesing Menggunakan Stopword Remover

### Keterangan Dataset

In [20]:
# Load dataset hasil scraping
file_path = os.path.join('Data', 'dataset_detik.csv')
df = pd.read_csv(file_path)

# 1. Cek Informasi Awal
print("Informasi Dataset Awal")
print(f"Total Baris Data : {len(df)} baris")
print(f"Daftar Fitur Awal : {list(df.columns)}")

# Buat kolom id jika belum tersedia pada dataset hasil scraping
if 'id' not in df.columns:
    df.insert(0, 'id', range(1, len(df) + 1))

# 2. Filter Fitur yang Digunakan
df = df[['id', 'isi_berita', 'label']].copy()

print(f"\nDaftar Fitur Digunakan : {list(df.columns)}")

print("\nKeterangan Fitur yang Digunakan:")
print("- id         : identitas unik untuk setiap berita")
print("- isi_berita : teks atau isi lengkap berita")
print("- label      : kategori berita, yaitu sport atau finance")

# 3. Tampilkan baris data
print("\nScraping Selesai! Data disimpan ke 'dataset_detik.csv'")
display(df.head(5))

Informasi Dataset Awal
Total Baris Data : 199 baris
Daftar Fitur Awal : ['id', 'isi_berita', 'label', 'url']

Daftar Fitur Digunakan : ['id', 'isi_berita', 'label']

Keterangan Fitur yang Digunakan:
- id         : identitas unik untuk setiap berita
- isi_berita : teks atau isi lengkap berita
- label      : kategori berita, yaitu sport atau finance

Scraping Selesai! Data disimpan ke 'dataset_detik.csv'

   id                                         isi_berita  label
0   1  Indonesia mencatatkan sejarah di dunia senam. ...  sport
1   2  Sean Gelael dan Team WRT 32 punya kans naik po...  sport
2   3  Tiga pebalap Team WRT 32 bakal bagi tugas akhi...  sport
3   4  Tim basket Hangtuah memanfaatkan turnamen pram...  sport
4   5  Atlet panahan Indonesia, Nurisa Dian Ashrifah,...  sport

### Inisialisasi Library Sastrawi

In [21]:
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Inisialisasi Sastrawi
stop_factory = StopWordRemoverFactory()
stopword_remover = stop_factory.create_stop_word_remover()

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

### Case Folding

In [22]:
# 1. Eksekusi Case Folding (mengubah huruf kapital menjadi huruf kecil)
df['step1_case_folding'] = df['isi_berita'].str.lower()

# 2. Tampilkan Perbandingan Sebelum dan Sesudah (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Case Folding (Tabel) ---")
display(df[['id', 'isi_berita', 'step1_case_folding', 'label']].head(3))

# 3. Tampilkan Detail Teks 1 Sampel Artikel untuk Membandingkan Karakter
print("\n --- Detail Contoh Teks Baris Pertama (ID: 1) --- ")
print("* Sebelum (isi_berita):")
print(df['isi_berita'].iloc[0][:200] + "...\n")

print("* Sesudah (step1_case_folding):")
print(df['step1_case_folding'].iloc[0][:200] + "...")

--- Perbandingan Sebelum & Sesudah Case Folding (Tabel) ---

,id,isi_berita,step1_case_folding,label
0,1,Indonesia mencatatkan sejarah di dunia senam. ...,indonesia mencatatkan sejarah di dunia senam. ...,sport
1,2,Sean Gelael dan Team WRT 32 punya kans naik po...,sean gelael dan team wrt 32 punya kans naik po...,sport
2,3,Tiga pebalap Team WRT 32 bakal bagi tugas akhi...,tiga pebalap team wrt 32 bakal bagi tugas akhi...,sport

 --- Detail Contoh Teks Baris Pertama (ID: 1) ---
* Sebelum (isi_berita):
Indonesia mencatatkan sejarah di dunia senam. Mereka jadi tuan rumah pertama untuk ajang Asian Gym fo Life Challenge 2026.
Ajang bernama lengkap 1st Asian Gym for Life Challenge 2026 presented by POZA...

* Sesudah (step1_case_folding):
indonesia mencatatkan sejarah di dunia senam. mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge 2026.
ajang bernama lengkap 1st asian gym for life challenge 2026 presented by poza...

### Cleaning

In [23]:
import re

In [24]:
# 1. Definisi fungsi cleaning
def clean_text(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # Hapus URL/link
    text = re.sub(r'\d+', '', text)                   # Hapus angka
    text = re.sub(r'[^\w\s]', ' ', text)              # Hapus tanda baca & simbol khusus
    text = re.sub(r'\s+', ' ', text).strip()          # Hapus spasi berlebih & spasi di awal/akhir
    return text

# 2. Terapkan cleaning pada hasil Case Folding (step1_case_folding)
df['step2_cleaning'] = df['step1_case_folding'].apply(clean_text)

# 3. Tampilkan Perbandingan Sebelum dan Sesudah Cleaning (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Cleaning (Tabel) ---")
display(df[['id', 'step1_case_folding', 'step2_cleaning', 'label']].head())

# 4. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\nDetail Contoh Teks Baris Pertama")
print("* Sebelum Cleaning (step1_case_folding):")
print(df['step1_case_folding'].iloc[0][:200] + "...\n")

print("* Sesudah Cleaning (step2_cleaning):")
print(df['step2_cleaning'].iloc[0][:200] + "...")

--- Perbandingan Sebelum & Sesudah Cleaning (Tabel) ---

,id,step1_case_folding,step2_cleaning,label
0,1,indonesia mencatatkan sejarah di dunia senam. ...,indonesia mencatatkan sejarah di dunia senam m...,sport
1,2,sean gelael dan team wrt 32 punya kans naik po...,sean gelael dan team wrt punya kans naik podiu...,sport
2,3,tiga pebalap team wrt 32 bakal bagi tugas akhi...,tiga pebalap team wrt bakal bagi tugas akhir p...,sport
3,4,tim basket hangtuah memanfaatkan turnamen pram...,tim basket hangtuah memanfaatkan turnamen pram...,sport
4,5,"atlet panahan indonesia, nurisa dian ashrifah,...",atlet panahan indonesia nurisa dian ashrifah m...,sport

Detail Contoh Teks Baris Pertama
* Sebelum Cleaning (step1_case_folding):
indonesia mencatatkan sejarah di dunia senam. mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge 2026.
ajang bernama lengkap 1st asian gym for life challenge 2026 presented by poza...

* Sesudah Cleaning (step2_cleaning):
indonesia mencatatkan sejarah di dunia senam mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge ajang bernama lengkap st asian gym for life challenge presented by poza sport academ...

### Tokenization

In [25]:
# 1. Terapkan Tokenization pada hasil Cleaning (step2_cleaning)
# Menggunakan .split() karena teks sudah bersih dari tanda baca
df['step3_tokenize'] = df['step2_cleaning'].apply(lambda x: x.split())

# 2. Tampilkan Perbandingan Sebelum dan Sesudah Tokenization (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Tokenization (Tabel) ===")
display(df[['id', 'step2_cleaning', 'step3_tokenize', 'label']].head())

# 3. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("* Sebelum Tokenization (step2_cleaning - Tipe Data: String):")
print(df['step2_cleaning'].iloc[0][:150] + "...\n")

print("* Sesudah Tokenization (step3_tokenize - Tipe Data: List of Tokens):")
print(df['step3_tokenize'].iloc[0][:15]) # Tampilkan 15 kata/token pertama

--- Perbandingan Sebelum & Sesudah Tokenization (Tabel) ===

,id,step2_cleaning,step3_tokenize,label
0,1,indonesia mencatatkan sejarah di dunia senam m...,"[indonesia, mencatatkan, sejarah, di, dunia, s...",sport
1,2,sean gelael dan team wrt punya kans naik podiu...,"[sean, gelael, dan, team, wrt, punya, kans, na...",sport
2,3,tiga pebalap team wrt bakal bagi tugas akhir p...,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",sport
3,4,tim basket hangtuah memanfaatkan turnamen pram...,"[tim, basket, hangtuah, memanfaatkan, turnamen...",sport
4,5,atlet panahan indonesia nurisa dian ashrifah m...,"[atlet, panahan, indonesia, nurisa, dian, ashr...",sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
* Sebelum Tokenization (step2_cleaning - Tipe Data: String):
indonesia mencatatkan sejarah di dunia senam mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge ajang bernama lengkap st asian gym...

* Sesudah Tokenization (step3_tokenize - Tipe Data: List of Tokens):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

### Normalisasi Slang & Istilah Asing

In [26]:
# 1. Definisi Kamus Normalisasi (Slang, Singkatan, & Istilah Asing/Olahraga/Keuangan)
kamus_normalisasi = {
    # Singkatan & Slang Umum Bahasa Indonesia
    'yg': 'yang',
    'dgn': 'dengan',
    'utk': 'untuk',
    'dr': 'dari',
    'sbg': 'sebagai',
    'tdk': 'tidak',
    'krn': 'karena',
    'sdh': 'sudah',
    'blm': 'belum',
    
    # Istilah Serapan / Inggris Kategori Sport & Finance
    'match': 'tanding',
    'coaching': 'pelatih',
    'coach': 'pelatih',
    'strikers': 'striker',
    'goal': 'gol',
    'percent': 'persen',
    'company': 'perusahaan',
    'tax': 'pajak'
}

# 2. Fungsi Normalisasi per List Token
def normalize_tokens(tokens):
    return [kamus_normalisasi.get(word, word) for word in tokens]

# 3. Terapkan Normalisasi pada step3_tokenize
df['step4_normalized'] = df['step3_tokenize'].apply(normalize_tokens)

# 4. Tampilkan Perbandingan Sebelum dan Sesudah Normalisasi (Tabel Pandas)
print("--- Perbandingan Sebelumnya & Sesudah Normalisasi (Tabel) ---")
display(df[['id', 'step3_tokenize', 'step4_normalized', 'label']].head())

# 5. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("* Sebelum Normalisasi (step3_tokenize):")
print(df['step3_tokenize'].iloc[0][:15])

print("\n* Sesudah Normalisasi (step4_normalized):")
print(df['step4_normalized'].iloc[0][:15])

--- Perbandingan Sebelumnya & Sesudah Normalisasi (Tabel) ---

,id,step3_tokenize,step4_normalized,label
0,1,"[indonesia, mencatatkan, sejarah, di, dunia, s...","[indonesia, mencatatkan, sejarah, di, dunia, s...",sport
1,2,"[sean, gelael, dan, team, wrt, punya, kans, na...","[sean, gelael, dan, team, wrt, punya, kans, na...",sport
2,3,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...","[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",sport
3,4,"[tim, basket, hangtuah, memanfaatkan, turnamen...","[tim, basket, hangtuah, memanfaatkan, turnamen...",sport
4,5,"[atlet, panahan, indonesia, nurisa, dian, ashr...","[atlet, panahan, indonesia, nurisa, dian, ashr...",sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
* Sebelum Normalisasi (step3_tokenize):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

* Sesudah Normalisasi (step4_normalized):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

### Stopword Removal

In [27]:
# 1. Terapkan Stopword Removal pada hasil Normalisasi (step4_normalized)
# List token digabung menjadi string (' '.join) agar dapat diproses oleh Sastrawi stopword_remover
df['step5_stopword'] = df['step4_normalized'].apply(
    lambda tokens: stopword_remover.remove(' '.join(tokens))
)

# 2. Tampilkan Perbandingan Sebelum dan Sesudah Stopword Removal (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Stopword Removal (Tabel) ---")
display(df[['id', 'step4_normalized', 'step5_stopword', 'label']].head())

# 3. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("* Sebelum Stopword Removal (step4_normalized):")
print(df['step4_normalized'].iloc[0][:15])

print("\n* Sesudah Stopword Removal (step5_stopword):")
print(df['step5_stopword'].iloc[0][:150] + "...")

--- Perbandingan Sebelum & Sesudah Stopword Removal (Tabel) ---

,id,step4_normalized,step5_stopword,label
0,1,"[indonesia, mencatatkan, sejarah, di, dunia, s...",indonesia mencatatkan sejarah dunia senam jadi...,sport
1,2,"[sean, gelael, dan, team, wrt, punya, kans, na...",sean gelael team wrt punya kans naik podium ho...,sport
2,3,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",tiga pebalap team wrt bakal tugas akhir pekan ...,sport
3,4,"[tim, basket, hangtuah, memanfaatkan, turnamen...",tim basket hangtuah memanfaatkan turnamen pram...,sport
4,5,"[atlet, panahan, indonesia, nurisa, dian, ashr...",atlet panahan indonesia nurisa dian ashrifah m...,sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
* Sebelum Stopword Removal (step4_normalized):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

* Sesudah Stopword Removal (step5_stopword):
indonesia mencatatkan sejarah dunia senam jadi tuan rumah pertama ajang asian gym fo life challenge ajang bernama lengkap st asian gym for life challe...

### Stemming

In [28]:
# 1. Terapkan Stemming pada hasil Stopword Removal (step5_stopword)
print("Sedang memproses Stemming (proses ini memakan waktu 1–3 menit)...")
df['step6_stemming'] = df['step5_stopword'].apply(lambda x: stemmer.stem(x))

# Tetapkan kolom hasil bersih akhir
df['isi_berita_clean'] = df['step6_stemming']

# 2. Tampilkan Perbandingan Sebelum dan Sesudah Stemming (Tabel Pandas)
print("\n--- Perbandingan Sebelum & Sesudah Stemming (Tabel) ---")
display(df[['id', 'step5_stopword', 'step6_stemming', 'label']].head(3))

# 3. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("* Sebelum Stemming (step5_stopword):")
print(df['step5_stopword'].iloc[0][:150] + "...\n")

print("* Sesudah Stemming (step6_stemming / isi_berita_clean):")
print(df['step6_stemming'].iloc[0][:150] + "...")

Sedang memproses Stemming (proses ini memakan waktu 1–3 menit)...

--- Perbandingan Sebelum & Sesudah Stemming (Tabel) ---

,id,step5_stopword,step6_stemming,label
0,1,indonesia mencatatkan sejarah dunia senam jadi...,indonesia catat sejarah dunia senam jadi tuan ...,sport
1,2,sean gelael team wrt punya kans naik podium ho...,sean gelael team wrt punya kans naik podium ho...,sport
2,3,tiga pebalap team wrt bakal tugas akhir pekan ...,tiga balap team wrt bakal tugas akhir pekan se...,sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
* Sebelum Stemming (step5_stopword):
indonesia mencatatkan sejarah dunia senam jadi tuan rumah pertama ajang asian gym fo life challenge ajang bernama lengkap st asian gym for life challe...

* Sesudah Stemming (step6_stemming / isi_berita_clean):
indonesia catat sejarah dunia senam jadi tuan rumah pertama ajang asi gym fo life challenge ajang nama lengkap st asi gym for life challenge presented...

In [51]:

from pathlib import Path
import pandas as pd

# Lokasi Data mengikuti folder kerja notebook
OUTPUT_DIR = Path.cwd() / "Data"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Pastikan hasil stemming sudah tersedia
if "isi_berita_clean" not in df.columns:
    raise KeyError(
        "Kolom isi_berita_clean belum ada. "
        "Jalankan dahulu sel preprocessing dan stemming."
    )

# Simpan hasil teks yang benar-benar sudah diproses
df_preprocessed = df[
    ["id", "isi_berita_clean", "label"]
].copy()

output_path = OUTPUT_DIR / "detik_preprocessed.csv"

df_preprocessed.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

# Verifikasi file benar-benar tersimpan dan terbaca
if output_path.exists():
    hasil_baca = pd.read_csv(output_path, encoding="utf-8-sig")

    print("BERHASIL DISIMPAN")
    print("Lokasi lengkap:", output_path.resolve())
    print("Ukuran file:", output_path.stat().st_size, "byte")
    print("Jumlah baris:", len(hasil_baca))
    print("Kolom:", hasil_baca.columns.tolist())
    display(hasil_baca.head())
else:
    raise OSError(f"File gagal dibuat: {output_path}")

BERHASIL DISIMPAN
Lokasi lengkap: D:\webmining\Data\detik_preprocessed.csv
Ukuran file: 414033 byte
Jumlah baris: 199
Kolom: ['id', 'isi_berita_clean', 'label']

   id                                   isi_berita_clean  label
0   1  indonesia catat sejarah di dunia senam mereka ...  sport
1   2  sean gelael dan team wrt punya kans naik podiu...  sport
2   3  tiga balap team wrt bakal bagi tugas akhir pek...  sport
3   4  tim basket hangtuah manfaat turnamen pramusim ...  sport
4   5  atlet panah indonesia nurisa dian ashrifah dap...  sport

## Preprocesing Tanpa Menggunakan Stopword Remover

### Keterangan Dataset

In [29]:
# Load dataset hasil scraping
file_path = os.path.join('Data', 'dataset_detik.csv')
df = pd.read_csv(file_path)

# 1. Cek Informasi Awal
print("Informasi Dataset Awal")
print(f"Total Baris Data : {len(df)} baris")
print(f"Daftar Fitur Awal : {list(df.columns)}")

# Buat kolom id jika belum tersedia pada dataset hasil scraping
if 'id' not in df.columns:
    df.insert(0, 'id', range(1, len(df) + 1))

# 2. Filter Fitur yang Digunakan
df = df[['id', 'isi_berita', 'label']].copy()

print(f"\nDaftar Fitur Digunakan : {list(df.columns)}")

print("\nKeterangan Fitur yang Digunakan:")
print("- id         : identitas unik untuk setiap berita")
print("- isi_berita : teks atau isi lengkap berita")
print("- label      : kategori berita, yaitu sport atau finance")

# 3. Tampilkan baris data
print("\nScraping Selesai! Data disimpan ke 'dataset_detik.csv'")
display(df.head(5))

Informasi Dataset Awal
Total Baris Data : 199 baris
Daftar Fitur Awal : ['id', 'isi_berita', 'label', 'url']

Daftar Fitur Digunakan : ['id', 'isi_berita', 'label']

Keterangan Fitur yang Digunakan:
- id         : identitas unik untuk setiap berita
- isi_berita : teks atau isi lengkap berita
- label      : kategori berita, yaitu sport atau finance

Scraping Selesai! Data disimpan ke 'dataset_detik.csv'

   id                                         isi_berita  label
0   1  Indonesia mencatatkan sejarah di dunia senam. ...  sport
1   2  Sean Gelael dan Team WRT 32 punya kans naik po...  sport
2   3  Tiga pebalap Team WRT 32 bakal bagi tugas akhi...  sport
3   4  Tim basket Hangtuah memanfaatkan turnamen pram...  sport
4   5  Atlet panahan Indonesia, Nurisa Dian Ashrifah,...  sport

### Inisialisasi Library Sastrawi

In [30]:
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Inisialisasi Sastrawi
stop_factory = StopWordRemoverFactory()
stopword_remover = stop_factory.create_stop_word_remover()

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

### Case Folding

In [31]:
# 1. Eksekusi Case Folding (mengubah huruf kapital menjadi huruf kecil)
df['step1_case_folding'] = df['isi_berita'].str.lower()

# 2. Tampilkan Perbandingan Sebelum dan Sesudah (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Case Folding (Tabel) ---")
display(df[['id', 'isi_berita', 'step1_case_folding', 'label']].head(3))

# 3. Tampilkan Detail Teks 1 Sampel Artikel untuk Membandingkan Karakter
print("\n --- Detail Contoh Teks Baris Pertama (ID: 1) --- ")
print("Sebelum (isi_berita):")
print(df['isi_berita'].iloc[0][:200] + "...\n")

print("Sesudah (step1_case_folding):")
print(df['step1_case_folding'].iloc[0][:200] + "...")

--- Perbandingan Sebelum & Sesudah Case Folding (Tabel) ---

,id,isi_berita,step1_case_folding,label
0,1,Indonesia mencatatkan sejarah di dunia senam. ...,indonesia mencatatkan sejarah di dunia senam. ...,sport
1,2,Sean Gelael dan Team WRT 32 punya kans naik po...,sean gelael dan team wrt 32 punya kans naik po...,sport
2,3,Tiga pebalap Team WRT 32 bakal bagi tugas akhi...,tiga pebalap team wrt 32 bakal bagi tugas akhi...,sport

 --- Detail Contoh Teks Baris Pertama (ID: 1) ---
Sebelum (isi_berita):
Indonesia mencatatkan sejarah di dunia senam. Mereka jadi tuan rumah pertama untuk ajang Asian Gym fo Life Challenge 2026.
Ajang bernama lengkap 1st Asian Gym for Life Challenge 2026 presented by POZA...

Sesudah (step1_case_folding):
indonesia mencatatkan sejarah di dunia senam. mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge 2026.
ajang bernama lengkap 1st asian gym for life challenge 2026 presented by poza...

### Cleaning

In [32]:
import re

In [33]:
# 1. Definisi fungsi cleaning
def clean_text(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # Hapus URL/link
    text = re.sub(r'\d+', '', text)                   # Hapus angka
    text = re.sub(r'[^\w\s]', ' ', text)              # Hapus tanda baca & simbol khusus
    text = re.sub(r'\s+', ' ', text).strip()          # Hapus spasi berlebih & spasi di awal/akhir
    return text

# 2. Terapkan cleaning pada hasil Case Folding (step1_case_folding)
df['step2_cleaning'] = df['step1_case_folding'].apply(clean_text)

# 3. Tampilkan Perbandingan Sebelum dan Sesudah Cleaning (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Cleaning (Tabel) ---")
display(df[['id', 'step1_case_folding', 'step2_cleaning', 'label']].head())

# 4. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\nDetail Contoh Teks Baris Pertama")
print("Sebelum Cleaning (step1_case_folding):")
print(df['step1_case_folding'].iloc[0][:200] + "...\n")

print("Sesudah Cleaning (step2_cleaning):")
print(df['step2_cleaning'].iloc[0][:200] + "...")

--- Perbandingan Sebelum & Sesudah Cleaning (Tabel) ---

,id,step1_case_folding,step2_cleaning,label
0,1,indonesia mencatatkan sejarah di dunia senam. ...,indonesia mencatatkan sejarah di dunia senam m...,sport
1,2,sean gelael dan team wrt 32 punya kans naik po...,sean gelael dan team wrt punya kans naik podiu...,sport
2,3,tiga pebalap team wrt 32 bakal bagi tugas akhi...,tiga pebalap team wrt bakal bagi tugas akhir p...,sport
3,4,tim basket hangtuah memanfaatkan turnamen pram...,tim basket hangtuah memanfaatkan turnamen pram...,sport
4,5,"atlet panahan indonesia, nurisa dian ashrifah,...",atlet panahan indonesia nurisa dian ashrifah m...,sport

Detail Contoh Teks Baris Pertama
Sebelum Cleaning (step1_case_folding):
indonesia mencatatkan sejarah di dunia senam. mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge 2026.
ajang bernama lengkap 1st asian gym for life challenge 2026 presented by poza...

Sesudah Cleaning (step2_cleaning):
indonesia mencatatkan sejarah di dunia senam mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge ajang bernama lengkap st asian gym for life challenge presented by poza sport academ...

### Tokenization

In [34]:
# 1. Terapkan Tokenization pada hasil Cleaning (step2_cleaning)
# Menggunakan .split() karena teks sudah bersih dari tanda baca
df['step3_tokenize'] = df['step2_cleaning'].apply(lambda x: x.split())

# 2. Tampilkan Perbandingan Sebelum dan Sesudah Tokenization (Tabel Pandas)
print("--- Perbandingan Sebelum & Sesudah Tokenization (Tabel) ===")
display(df[['id', 'step2_cleaning', 'step3_tokenize', 'label']].head())

# 3. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("Sebelum Tokenization (step2_cleaning - Tipe Data: String):")
print(df['step2_cleaning'].iloc[0][:150] + "...\n")

print("Sesudah Tokenization (step3_tokenize - Tipe Data: List of Tokens):")
print(df['step3_tokenize'].iloc[0][:15]) # Tampilkan 15 kata/token pertama

--- Perbandingan Sebelum & Sesudah Tokenization (Tabel) ===

,id,step2_cleaning,step3_tokenize,label
0,1,indonesia mencatatkan sejarah di dunia senam m...,"[indonesia, mencatatkan, sejarah, di, dunia, s...",sport
1,2,sean gelael dan team wrt punya kans naik podiu...,"[sean, gelael, dan, team, wrt, punya, kans, na...",sport
2,3,tiga pebalap team wrt bakal bagi tugas akhir p...,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",sport
3,4,tim basket hangtuah memanfaatkan turnamen pram...,"[tim, basket, hangtuah, memanfaatkan, turnamen...",sport
4,5,atlet panahan indonesia nurisa dian ashrifah m...,"[atlet, panahan, indonesia, nurisa, dian, ashr...",sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
Sebelum Tokenization (step2_cleaning - Tipe Data: String):
indonesia mencatatkan sejarah di dunia senam mereka jadi tuan rumah pertama untuk ajang asian gym fo life challenge ajang bernama lengkap st asian gym...

Sesudah Tokenization (step3_tokenize - Tipe Data: List of Tokens):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

### Normalisasi Slang & Istilah Asing

In [35]:
# 1. Definisi Kamus Normalisasi (Slang, Singkatan, & Istilah Asing/Olahraga/Keuangan)
kamus_normalisasi = {
    # Singkatan & Slang Umum Bahasa Indonesia
    'yg': 'yang',
    'dgn': 'dengan',
    'utk': 'untuk',
    'dr': 'dari',
    'sbg': 'sebagai',
    'tdk': 'tidak',
    'krn': 'karena',
    'sdh': 'sudah',
    'blm': 'belum',
    
    # Istilah Serapan / Inggris Kategori Sport & Finance
    'match': 'tanding',
    'coaching': 'pelatih',
    'coach': 'pelatih',
    'strikers': 'striker',
    'goal': 'gol',
    'percent': 'persen',
    'company': 'perusahaan',
    'tax': 'pajak'
}

# 2. Fungsi Normalisasi per List Token
def normalize_tokens(tokens):
    return [kamus_normalisasi.get(word, word) for word in tokens]

# 3. Terapkan Normalisasi pada step3_tokenize
df['step4_normalized'] = df['step3_tokenize'].apply(normalize_tokens)

# 4. Tampilkan Perbandingan Sebelum dan Sesudah Normalisasi (Tabel Pandas)
print("--- Perbandingan Sebelumnya & Sesudah Normalisasi (Tabel) ---")
display(df[['id', 'step3_tokenize', 'step4_normalized', 'label']].head())

# 5. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")
print("Sebelum Normalisasi (step3_tokenize):")
print(df['step3_tokenize'].iloc[0][:15])

print("\nSesudah Normalisasi (step4_normalized):")
print(df['step4_normalized'].iloc[0][:15])

--- Perbandingan Sebelumnya & Sesudah Normalisasi (Tabel) ---

,id,step3_tokenize,step4_normalized,label
0,1,"[indonesia, mencatatkan, sejarah, di, dunia, s...","[indonesia, mencatatkan, sejarah, di, dunia, s...",sport
1,2,"[sean, gelael, dan, team, wrt, punya, kans, na...","[sean, gelael, dan, team, wrt, punya, kans, na...",sport
2,3,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...","[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",sport
3,4,"[tim, basket, hangtuah, memanfaatkan, turnamen...","[tim, basket, hangtuah, memanfaatkan, turnamen...",sport
4,5,"[atlet, panahan, indonesia, nurisa, dian, ashr...","[atlet, panahan, indonesia, nurisa, dian, ashr...",sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
Sebelum Normalisasi (step3_tokenize):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

Sesudah Normalisasi (step4_normalized):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym']

### Stemming

In [43]:
# 1. Terapkan Stemming pada hasil Stopword Removal
print("Sedang memproses Stemming (proses ini memakan waktu 1–3 menit)...")

# Jika step4_normalized berisi list token,
# lakukan stemming pada setiap kata lalu gabungkan kembali menjadi teks.
df['step5_stemming'] = df['step4_normalized'].apply(
    lambda tokens: ' '.join(
        stemmer.stem(str(token))
        for token in tokens
    ) if isinstance(tokens, list)
    else stemmer.stem(str(tokens))
)

# Tetapkan kolom hasil bersih akhir
df['isi_berita_clean'] = df['step5_stemming']

# 2. Tampilkan Perbandingan Sebelum dan Sesudah Stemming
print("\n--- Perbandingan Sebelum & Sesudah Stemming (Tabel) ---")
display(
    df[['id', 'step4_normalized', 'step5_stemming', 'label']].head(3)
)

# 3. Tampilkan Detail Teks 1 Sampel Artikel (ID: 1)
print("\n--- Detail Contoh Teks Baris Pertama (ID: 1) ---")

print("Sebelum Stemming (step4_normalized):")
print(str(df['step4_normalized'].iloc[0])[:150] + "...\n")

print("Sesudah Stemming (step5_stemming / isi_berita_clean):")
print(str(df['step5_stemming'].iloc[0])[:150] + "...")

Sedang memproses Stemming (proses ini memakan waktu 1–3 menit)...

--- Perbandingan Sebelum & Sesudah Stemming (Tabel) ---

,id,step4_normalized,step5_stemming,label
0,1,"[indonesia, mencatatkan, sejarah, di, dunia, s...",indonesia catat sejarah di dunia senam mereka ...,sport
1,2,"[sean, gelael, dan, team, wrt, punya, kans, na...",sean gelael dan team wrt punya kans naik podiu...,sport
2,3,"[tiga, pebalap, team, wrt, bakal, bagi, tugas,...",tiga balap team wrt bakal bagi tugas akhir pek...,sport

--- Detail Contoh Teks Baris Pertama (ID: 1) ---
Sebelum Stemming (step4_normalized):
['indonesia', 'mencatatkan', 'sejarah', 'di', 'dunia', 'senam', 'mereka', 'jadi', 'tuan', 'rumah', 'pertama', 'untuk', 'ajang', 'asian', 'gym', 'fo', ...

Sesudah Stemming (step5_stemming / isi_berita_clean):
indonesia catat sejarah di dunia senam mereka jadi tuan rumah pertama untuk ajang asi gym fo life challenge ajang nama lengkap st asi gym for life cha...

In [52]:

from pathlib import Path
import pandas as pd

OUTPUT_DIR = Path.cwd() / "Data"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if "isi_berita_clean" not in df.columns:
    raise KeyError(
        "Kolom isi_berita_clean belum ada. "
        "Jalankan dahulu sel preprocessing dan stemming."
    )

df_preprocessed = df[
    ["id", "isi_berita_clean", "label"]
].copy()

output_path = OUTPUT_DIR / "detik_preprocessed-TanpaStopword.csv"

df_preprocessed.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

if output_path.exists():
    hasil_baca = pd.read_csv(output_path, encoding="utf-8-sig")

    print("BERHASIL DISIMPAN")
    print("Lokasi lengkap:", output_path.resolve())
    print("Ukuran file:", output_path.stat().st_size, "byte")
    print("Jumlah baris:", len(hasil_baca))
    print("Kolom:", hasil_baca.columns.tolist())
    display(hasil_baca.head())
else:
    raise OSError(f"File gagal dibuat: {output_path}")

BERHASIL DISIMPAN
Lokasi lengkap: D:\webmining\Data\detik_preprocessed-TanpaStopword.csv
Ukuran file: 414033 byte
Jumlah baris: 199
Kolom: ['id', 'isi_berita_clean', 'label']

   id                                   isi_berita_clean  label
0   1  indonesia catat sejarah di dunia senam mereka ...  sport
1   2  sean gelael dan team wrt punya kans naik podiu...  sport
2   3  tiga balap team wrt bakal bagi tugas akhir pek...  sport
3   4  tim basket hangtuah manfaat turnamen pramusim ...  sport
4   5  atlet panah indonesia nurisa dian ashrifah dap...  sport